# Generated by Django 2.0.6 on 2019-02-28 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewCarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=50)),
                ('modelYear', models.DateField(default=datetime.date(2019, 2, 28))),
                ('mpg', models.IntegerField(default=0)),
            ],
        ),
    ]
