# Generated by Django 2.0.6 on 2019-02-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcarmodel',
            name='mpg',
            field=models.IntegerField(default=20),
        ),
    ]
